version: "3.8"

services:
  model_service:
    build: ../services/model_service
    container_name: model_service
    ports:
      - "8000:8000"

  api_service:
    build: ../services/api
    container_name: api_service
    ports:
      - "8080:8080"
    depends_on:
      - model_service

volumes: {}